server:
  port: 8081
spring:
  application:
    name: user-service-provider
dubbo:
  application:
    name: dubbo-provider
  protocol:
    port: 20880 # 暴露的端口号
  registry:
    address: zookeeper://localhost:2181?init.timeout=60000 # 注册中心
  scan:
    base-packages: com.xiaobaicai.api.impl # 扫描的包名
  provider:
    token: true # 是否提供服务
