server:
  port: 8888
#TkMybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xiaobaicai.tkmybatis.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb2020?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: cjy123456
    username: root